
server:
    port: 9041

spring:
    application:
        name: spring-cloud-monitor

#management:
    #port: 8801

applications: spring-cloud-consul-consumer

turbine:
    aggregator:
        clusterConfig: ${applications}
    appConfig: ${applications}
    #指定了需要收集监控信息的服务名；以逗号分隔
    cluster-name-expression: new String("default")
    #集群命名 注意：new String("default")这个一定要用 String 来包一下
    combine-host-port: true
    #参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以 host 来区分不同的服务，这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计。


