
server:
    port: 8701
    servlet:
        context-path: /cloudApi

spring:
    application:
        name: consul-provider
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                serviceName: service-consul-provider
                healthCheckPath: /cloudApi/actuator/health
                healthCheckInterval: 15s

