
server:
    port: 9101

spring:
    application:
        name: service-consul-consumer-feign
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                # 指定注册到consul server上的服务名称
                serviceName: service-consul-consumer-feign



